// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfGrjo0AG7aPuXO3zpW8EyO03KkRRcEg',
    appId: '1:450700197291:web:5a7fe22d4980bdc71966ee',
    messagingSenderId: '450700197291',
    projectId: 'sgfirebaseappscholl7th',
    authDomain: 'sgfirebaseappscholl7th.firebaseapp.com',
    storageBucket: 'sgfirebaseappscholl7th.firebasestorage.app',
    measurementId: 'G-NSZ3JQXGT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwpytOBTcATBZ5J78DBLEfKc9p6FW6TZE',
    appId: '1:450700197291:android:6c9f42ea88695e471966ee',
    messagingSenderId: '450700197291',
    projectId: 'sgfirebaseappscholl7th',
    storageBucket: 'sgfirebaseappscholl7th.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0TbBoiFnZAiUL7CTmpgvT9EgVhWhPRuU',
    appId: '1:450700197291:ios:dac82ee96e77f1181966ee',
    messagingSenderId: '450700197291',
    projectId: 'sgfirebaseappscholl7th',
    storageBucket: 'sgfirebaseappscholl7th.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0TbBoiFnZAiUL7CTmpgvT9EgVhWhPRuU',
    appId: '1:450700197291:ios:dac82ee96e77f1181966ee',
    messagingSenderId: '450700197291',
    projectId: 'sgfirebaseappscholl7th',
    storageBucket: 'sgfirebaseappscholl7th.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcfGrjo0AG7aPuXO3zpW8EyO03KkRRcEg',
    appId: '1:450700197291:web:bec60a3410569cf11966ee',
    messagingSenderId: '450700197291',
    projectId: 'sgfirebaseappscholl7th',
    authDomain: 'sgfirebaseappscholl7th.firebaseapp.com',
    storageBucket: 'sgfirebaseappscholl7th.firebasestorage.app',
    measurementId: 'G-ZG2F7N77FW',
  );

}